apiVersion: batch/v1
kind: CronJob
metadata:
  name: helm-cleanup
  namespace: default
spec:
  schedule: "0 0 * * *" # Runs daily at midnight
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: helm
            image: alpine/helm:latest
            command:
            - /bin/sh
            - -c
            - |
              helm list --output json | jq -r '.[] | select(.updated < now - 7*24*60*60) | .name' | xargs -I {} helm uninstall {}
          restartPolicy: OnFailure
